-- MySQL Script generated by MySQL Workbench
-- qua 14 mai 2025 10:15:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_Albuns
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_Albuns
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_Albuns` ;
USE `db_Albuns` ;

-- -----------------------------------------------------
-- Table `db_Albuns`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Albuns`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nickUsuario` VARCHAR(20) NULL,
  `nmUsuario` VARCHAR(250) NULL,
  `dtnascUsuario` DATE NULL,
  `emailUsuario` VARCHAR(200) NULL,
  `senhaUsuario` VARCHAR(200) NULL,
  `paisUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_Albuns`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Albuns`.`Autor` (
  `idAutor` INT NOT NULL,
  `nmAutor` VARCHAR(45) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_Albuns`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Albuns`.`Album` (
  `idAlbum` INT NOT NULL,
  `nmAlbum` VARCHAR(1000) NULL,
  `dtAlbum` DATE NULL,
  `gnrAlbum` VARCHAR(45) NULL,
  `idAutor` INT NOT NULL,
  PRIMARY KEY (`idAlbum`, `idAutor`),
  INDEX `fk_Album_Autor1_idx` (`idAutor` ASC) VISIBLE,
  CONSTRAINT `fk_Album_Autor1`
    FOREIGN KEY (`idAutor`)
    REFERENCES `db_Albuns`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_Albuns`.`Musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Albuns`.`Musica` (
  `idMusica` INT NOT NULL,
  `nmMusica` VARCHAR(45) NULL,
  `duracaoMusica` VARCHAR(45) NULL,
  `Autor_idAutor` INT NOT NULL,
  PRIMARY KEY (`idMusica`, `Autor_idAutor`),
  INDEX `fk_Musica_Autor1_idx` (`Autor_idAutor` ASC) VISIBLE,
  CONSTRAINT `fk_Musica_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `db_Albuns`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_Albuns`.`UsuarioAlbum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Albuns`.`UsuarioAlbum` (
  `Nota` VARCHAR(45) NULL,
  `idUsuario` INT NOT NULL,
  `idAlbum` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `idAlbum`),
  INDEX `fk_UsuarioAlbum_Usuario_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_UsuarioAlbum_Album1_idx` (`idAlbum` ASC) VISIBLE,
  CONSTRAINT `fk_UsuarioAlbum_Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `db_Albuns`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsuarioAlbum_Album1`
    FOREIGN KEY (`idAlbum`)
    REFERENCES `db_Albuns`.`Album` (`idAlbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
